version: '3.9'

services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    # ports:
    #   - 3007:80
    environment:
      # - NEXT_PUBLIC_API_URL=http://localhost:4000
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:3005
    restart: always
    depends_on:
      - backend
    network_mode: host
  backend:
    network_mode: host
    container_name: backend
    image: backend
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    # ports:
    #   - 3005:80
    environment:
      - DATABASE_URL=postgresql://taylortheory:postgres@localhost:5432/postgres?schema=public
  db:
    container_name: db
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_USER: taylortheory
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
volumes:
  pgdata: {}